- name: Validate & Update
  env:
    PAYLOAD: ${{ github.event.client_payload }}
  run: |
    KEY=$(echo "$PAYLOAD" | jq -r '.key // empty' | tr -d '[:space:]')
    TYPE=$(echo "$PAYLOAD" | jq -r '.type // empty')
    DATA=$(echo "$PAYLOAD" | jq -c '.data // empty')

    if [ -z "$KEY" ]; then
      echo "Missing key"
      exit 1
    fi

    TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    cat > api/data.json <<EOF
    {
      "key": "$KEY",
      "lastUpdate": "$TIMESTAMP",
      "$TYPE": $DATA
    }
    EOF

    git add api/data.json
    git commit -m "Update $TYPE" || echo "No changes"
    git push || echo "Push failed"