name: Update Roblox Game Tree

on:
  repository_dispatch:
    types: [roblox_tree]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate & Update
        env:
          PAYLOAD: ${{ github.event.client_payload }}
          SESSION_KEY: ${{ secrets.SESSION_KEY }}
        run: |
          KEY=$(echo "$PAYLOAD" | jq -r .key)
          TREE=$(echo "$PAYLOAD" | jq -c .tree)

          if [ "$KEY" != "$SESSION_KEY" ]; then
            echo "Invalid session key"
            exit 1
          fi

          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          cat > api/data.json <<EOF
          {
            "lastUpdate": "$TIMESTAMP",
            "tree": $TREE
          }
          EOF

          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"
          git add api/data.json
          git commit -m "Game tree update - $TIMESTAMP"
          git push || echo "No changes to push"