name: Update Roblox Parts

on:
  repository_dispatch:
    types: [roblox_parts]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Validate & Update
        env:
          PAYLOAD: ${{ github.event.client_payload }}
        run: |
          KEY=$(echo "$PAYLOAD" | jq -r .key)
          PARTS=$(echo "$PAYLOAD" | jq -c .parts)

          # NO SECRET — KEY IS IN PAYLOAD
          if [ -z "$KEY" ] || [ "$KEY" = "null" ]; then
            echo "Missing key"
            exit 1
          fi

          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          cat > api/data.json <<EOF
          {
            "lastUpdate": "$TIMESTAMP",
            "key": "$KEY",
            "parts": $PARTS
          }
          EOF

          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"
          git add api/data.json
          git commit -m "Parts update - $TIMESTAMP" || echo "No changes"
          git push || echo "Push failed"